class StaticContent {
  StaticContent._();

  static const privacyPolicy =
      'TapEvent menghargai privasi Anda. Kebijakan '
      'ini menjelaskan bagaimana kami mengumpulkan, menggunakan, dan melindungi '
      'data pribadi Anda saat menggunakan aplikasi TapEvent.\n\n'
      '# Data yang Kami Kumpulkan\n'
      '- Data akun: nama lengkap, email, NIM/NIDN, dan nomor telepon.\n'
      '- Data event: informasi pendaftaran, kehadiran, dan aktivitas Anda pada '
      'setiap event.\n'
      '- Data perangkat: informasi teknis seperti versi aplikasi dan jenis '
      'perangkat untuk perbaikan layanan.\n\n'
      '# Penggunaan Data\n'
      '- Memproses pendaftaran dan pencatatan kehadiran event.\n'
      '- Mengelola akun dan memverifikasi identitas pengguna.\n'
      '- Memberikan notifikasi terkait event yang Anda ikuti.\n'
      '- Meningkatkan kualitas dan keamanan layanan aplikasi.\n\n'
      '# Penyimpanan dan Keamanan\n'
      'Data Anda disimpan dengan aman di server dan hanya diakses oleh pihak '
      'yang berwenang dalam lingkup kampus. Kami menerapkan langkah keamanan '
      'untuk mencegah akses, pengubahan, atau penyebaran data tanpa izin.\n\n'
      '# Berbagi Data\n'
      'Kami tidak menjual atau menyewakan data pribadi Anda kepada pihak lain. '
      'Data hanya dibagikan kepada penyelenggara event dalam lingkup internal '
      'kampus sesuai kebutuhan.\n\n'
      '# Hak Anda\n'
      '- Mengakses dan memperbarui data pribadi melalui menu Data Pribadi.\n'
      '- Menghapus akun dan meminta penjelasan terkait penggunaan data Anda.\n'
      '- Mengajukan pertanyaan atau keluhan terkait privasi kepada pengelola '
      'aplikasi.\n\n'
      '# Perubahan Kebijakan\n'
      'Kebijakan ini dapat diperbarui sewaktu-waktu. Perubahan akan '
      'diinformasikan melalui aplikasi. Dengan terus menggunakan TapEvent, '
      'Anda menyetujui kebijakan yang berlaku.';

  static const help =
      'Temukan jawaban dari pertanyaan yang paling sering diajukan tentang '
      'penggunaan TapEvent.\n\n'
      '# Bagaimana cara mendaftar event?\n'
      'Buka halaman event yang ingin diikuti, lalu tekan tombol Daftar atau '
      'Formulir Pendaftaran. Ikuti petunjuk hingga pendaftaran selesai.\n\n'
      '# Bagaimana melihat riwayat event saya?\n'
      'Masuk ke menu Saya, lalu pilih Riwayat Event untuk melihat event yang '
      'pernah diikuti dan mengunduh bukti kehadiran.\n\n'
      '# Bagaimana mengubah data pribadi?\n'
      'Masuk ke menu Saya, lalu pilih Data Pribadi untuk memperbarui nama, '
      'NIM/NIDN, nomor telepon, dan foto profil.\n\n'
      '# Bagaimana mengubah password?\n'
      'Masuk ke menu Saya, lalu pilih Keamanan dan isi password baru minimal '
      '6 karakter.\n\n'
      '# Bagaimana cara absensi lewat QR?\n'
      'Buka halaman detail event, lalu tekan tombol Scan dan arahkan kamera ke '
      'QR code dari penyelenggara untuk mencatat kehadiran Anda.\n\n'
      '# Mengapa event saya belum tampil?\n'
      'Event yang diajukan perlu disetujui admin terlebih dahulu sebelum '
      'tampil dan dapat didaftarkan oleh peserta.\n\n'
      '# Siapa yang bisa saya hubungi jika kendala?\n'
      'Hubungi pengelola TapEvent di kampus Anda melalui kontak resmi. '
      'Sertakan detail masalah agar dapat ditangani lebih cepat.';

  static const about =
      'TapEvent adalah platform digital untuk mengelola event kampus — mulai '
      'dari menjelajah dan mendaftar event, pencatatan kehadiran, hingga '
      'riwayat partisipasi.\n\n'
      '# Fitur Utama\n'
      '- Jelajah dan cari event kampus terbaru.\n'
      '- Pendaftaran event secara online.\n'
      '- Absensi melalui pemindaian QR code.\n'
      '- Riwayat event dan unduhan bukti kehadiran.\n'
      '- Manajemen event untuk penyelenggara dan admin.\n\n'
      '# Dibuat Untuk\n'
      'Mahasiswa, dosen, dan penyelenggara event di lingkungan kampus agar '
      'seluruh kegiatan berjalan lebih mudah, terorganisir, dan '
      'terdokumentasi.\n\n'
      '# Versi Aplikasi\n'
      'Versi 1.0.0\n\n'
      '# Kontak\n'
      'Untuk pertanyaan, saran, dan dukungan, silakan hubungi pengelola '
      'aplikasi melalui kanal resmi kampus.';
}
